// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.23.8";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts from Shivraj Enterprise (title, slug, excerpt, published date, cover image).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum posts to return (1-50, default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select("id, title, slug, excerpt, published_at, cover_image_url").eq("published", true).order("published_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.23.8";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Get a single published blog post from Shivraj Enterprise by its slug, including full content.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Blog post slug, e.g. 'gst-tds-manpower-supply-guide'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select("id, title, slug, excerpt, content, published_at, cover_image_url").eq("published", true).eq("slug", slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No published post found for slug '${slug}'.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/get-rate-card.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_rate_card_default = defineTool3({
  name: "get_rate_card",
  title: "Get manpower rate card",
  description: "Get the public rate card for Shivraj Enterprise manpower supply services (service, 8-hour and 12-hour rates and units).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("rate_card_items").select("service, rate8, unit8, rate12, unit12, sort_order").order("sort_order", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-company-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
var COMPANY_INFO = {
  name: "SHIVRAJ ENTERPRISE PVT. LTD.",
  tagline: "Manpower supply, outsourcing and industrial housekeeping in Vapi GIDC, Gujarat.",
  services: [
    "Manpower Outsourcing Services (with PF, ESIC and wages compliance)",
    "Manpower Supply Services for factories, warehouses and commercial sites",
    "Industrial Housekeeping Solutions",
    "Loading, unloading and general helpers",
    "Security and support staff deployment"
  ],
  compliance: [
    "GST-compliant invoicing (18% on manpower supply)",
    "TDS handling under Section 194C",
    "ESI and EPF managed for deployed workers",
    "Registered under the Contract Labour (Regulation & Abolition) Act"
  ],
  primaryLocation: "Vapi GIDC, Gujarat, India",
  contact: {
    email: "shivrajenterprise1234@gmail.com",
    phone: "+91 99984 98311",
    website: "https://shivraj-enterprise.lovable.app"
  },
  contactPage: "https://shivraj-enterprise.lovable.app/#/contact"
};
var get_company_info_default = defineTool4({
  name: "get_company_info",
  title: "Get Shivraj Enterprise company info",
  description: "Get public company profile for Shivraj Enterprise Pvt. Ltd.: services offered, compliance handled, location, and how to contact them for a quote.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(COMPANY_INFO) }],
    structuredContent: COMPANY_INFO
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "shivraj-enterprise-mcp",
  title: "Shivraj Enterprise MCP",
  version: "0.1.0",
  instructions: "Public tools for Shivraj Enterprise Pvt. Ltd. \u2014 a manpower supply, outsourcing and industrial housekeeping company in Vapi GIDC, Gujarat. Use `get_company_info` for services, compliance and contact details; `get_rate_card` for public per-shift manpower rates; `list_blog_posts` and `get_blog_post` for published compliance guides (GST, TDS, ESI/EPF).",
  tools: [get_company_info_default, get_rate_card_default, list_blog_posts_default, get_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
