// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlkirnhrofyqcedlixrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsa2lybmhyb2Z5cWNlZGxpeHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTIxOTYsImV4cCI6MjA1OTY2ODE5Nn0.YIkoZkjJtGNK7YYgOMhZzuushTty83irWlQDE_5GiB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);